env:
- namespace: "developer-hub"
  companyname: "Swinney IO"
  gitopsnamespace: "janus-argocd"
  gitopsinfranamespace: "infra-argocd"
  pipelinesnamespace: "janus-pipelines"
  vaultconfignamespace: "vault-config-operator"
  vaultnamespace: "vault"
  gitwebhooknamespace: "gitwebhook-operator"
  janusinstancename: "janus-dev"
  githubinfraorganization: "swinneyio"
  githubinfrarevision: "main"
